In [1]:
import numpy as np
import torch
import csv

from tqdm.notebook import tqdm

In [2]:
torch.cuda.is_available()

True

In [324]:
from google.colab import files

In [325]:

uploaded_file = files.upload()

Saving NEW_TANULO_AutoCatalysis_parameters_Rev0.5.csv to NEW_TANULO_AutoCatalysis_parameters_Rev0.5.csv


In [326]:
list(uploaded_file.keys())[0]

'NEW_TANULO_AutoCatalysis_parameters_Rev0.5.csv'

In [327]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [328]:


df = pd.read_csv(list(uploaded_file.keys())[0], delimiter= ';')
df

Type    k1     k2    k3    k4    k5     k6    k3r    k6r
0        1  9.03   4.92  2.52  1.11  7.65   6.14   5.04   0.00
1        1  8.36   3.52  5.59  0.44  8.74   4.70  11.18   0.00
2        1  4.21   7.55  2.36  1.02  3.87   3.54   4.72   0.00
3        1  9.54   7.75  1.24  2.14  6.27   4.75   2.48   0.00
4        1  9.96   5.49  2.88  1.09  1.99   7.40   5.76   0.00
...    ...   ...    ...   ...   ...   ...    ...    ...    ...
2695     3  5.71   8.85  9.14  9.14  8.15   9.28   0.00  18.56
2696     3  1.51  10.00  1.95  1.87  1.27   7.74   0.00  15.48
2697     3  9.59  10.00  8.67  4.62  2.93   1.88  17.34   0.00
2698     3  6.98   8.65  6.46  8.40  2.29   8.19   0.00  16.38
2699     3  5.90   0.39  1.01  5.43  3.30  10.00   0.00  20.00

[2700 rows x 9 columns]

In [329]:
train_df, val_df = train_test_split(df, test_size=0.2)

In [330]:
val_df

Type    k1    k2    k3    k4     k5    k6    k3r    k6r
1312     2  1.42  8.32  3.51  9.55   2.43  8.14   0.00  16.28
107      1  8.62  8.07  9.77  2.01   7.68  2.08  19.54   0.00
745      1  8.12  6.31  9.39  1.67   9.03  1.92  18.78   0.00
891      1  7.15  1.78  3.79  2.13   6.51  2.16   7.58   0.00
1961     3  8.16  4.26  8.06  5.53   1.45  3.89  16.12   0.00
...    ...   ...   ...   ...   ...    ...   ...    ...    ...
632      1  5.91  6.61  9.95  1.22   4.85  0.17  19.90   0.00
1719     2  3.11  5.47  1.17  9.18   7.21  0.57   0.00   1.14
2682     3  3.06  1.05  7.15  6.22   3.89  0.86   0.00   1.72
1030     2  2.39  7.30  2.31  8.26  10.00  8.24   0.00  16.48
1490     2  0.63  3.00  2.54  2.09   9.96  0.66   0.00   1.32

[540 rows x 9 columns]

In [331]:
train_df

Type    k1    k2    k3    k4     k5    k6    k3r    k6r
995      2  0.55  5.91  3.91  3.93   7.98  8.47   0.00  16.94
571      1  5.84  2.18  6.23  1.08   1.27  7.84  12.46   0.00
1989     3  8.07  0.54  9.81  8.84   3.90  1.95   0.00   3.90
432      1  4.19  6.52  5.35  1.20   3.97  7.33  10.70   0.00
727      1  7.97  9.38  9.01  2.28   7.69  5.42  18.02   0.00
...    ...   ...   ...   ...   ...    ...   ...    ...    ...
2046     3  8.94  1.38  4.20  5.16   2.37  6.50   8.40   0.00
1243     2  1.71  6.53  7.90  6.18   0.23  3.33   0.00   6.66
40       1  9.37  8.06  2.67  0.67  10.00  7.24   5.34   0.00
1344     2  1.92  7.54  5.47  9.10   1.57  4.34   0.00   8.68
583      1  7.20  5.90  4.58  0.43   8.37  9.01   9.16   0.00

[2160 rows x 9 columns]

In [332]:
train_df.values

array([[ 2.  ,  0.55,  5.91, ...,  8.47,  0.  , 16.94],
       [ 1.  ,  5.84,  2.18, ...,  7.84, 12.46,  0.  ],
       [ 3.  ,  8.07,  0.54, ...,  1.95,  0.  ,  3.9 ],
       ...,
       [ 1.  ,  9.37,  8.06, ...,  7.24,  5.34,  0.  ],
       [ 2.  ,  1.92,  7.54, ...,  4.34,  0.  ,  8.68],
       [ 1.  ,  7.2 ,  5.9 , ...,  9.01,  9.16,  0.  ]])

In [333]:
torch.Tensor(train_df.values)[:,1:9]

tensor([[ 0.5500,  5.9100,  3.9100,  ...,  8.4700,  0.0000, 16.9400],
        [ 5.8400,  2.1800,  6.2300,  ...,  7.8400, 12.4600,  0.0000],
        [ 8.0700,  0.5400,  9.8100,  ...,  1.9500,  0.0000,  3.9000],
        ...,
        [ 9.3700,  8.0600,  2.6700,  ...,  7.2400,  5.3400,  0.0000],
        [ 1.9200,  7.5400,  5.4700,  ...,  4.3400,  0.0000,  8.6800],
        [ 7.2000,  5.9000,  4.5800,  ...,  9.0100,  9.1600,  0.0000]])

In [334]:
import torch.utils.data as data
class KDataset(data.Dataset):

    def __init__(self, df, n_labels=3):
        """
        Inputs:
            df - pandas dataframe containing the data
        """
        super().__init__()
        self.n_labels = n_labels
        self.data = df
        self.ks = df.values[:, 1:9].astype(np.float32)
        self.labels = df.values[:, 0].astype(int)-1

    def __len__(self):
        # Number of data points
        return len(self.data)

    def __getitem__(self, i):
        # Return the i-th data point of the dataset
        k_values = self.ks[i]
        label = self.labels[i]
        labels = torch.tensor([1 if i==label else 0 for i in range(self.n_labels)])
        return k_values, labels

In [335]:
train_ds = KDataset(train_df)
print("Size of dataset:", len(train_ds))
print("Data point 0:", train_ds[0])

Size of dataset: 2160
Data point 0: (array([ 0.55,  5.91,  3.91,  3.93,  7.98,  8.47,  0.  , 16.94],
      dtype=float32), tensor([0, 1, 0]))


In [336]:
val_ds = KDataset(val_df)
print("Size of dataset:", len(val_ds))
print("Data point 0:", val_ds[0])

Size of dataset: 540
Data point 0: (array([ 1.42,  8.32,  3.51,  9.55,  2.43,  8.14,  0.  , 16.28],
      dtype=float32), tensor([0, 1, 0]))


In [337]:
train_loader = data.DataLoader(train_ds, batch_size=32, shuffle=True, drop_last=True)
val_loader = data.DataLoader(val_ds, batch_size=32, shuffle=False, drop_last=True)

In [338]:
data_inputs, data_labels = next(iter(train_loader))

# The shape of the outputs are [batch_size, d_1,...,d_N] where d_1,...,d_N are the
# dimensions of the data point returned from the dataset class
print("Data inputs", data_inputs.shape, "\n", data_inputs)
print("Data labels", data_labels.shape, "\n", data_labels)

Data inputs torch.Size([32, 8]) 
 tensor([[ 3.5500,  2.9500,  6.7700,  0.4000,  9.1000,  7.2900, 13.5400,  0.0000],
        [ 1.0100,  1.9600,  7.1100,  7.8300,  8.4700,  0.5500,  0.0000,  1.1000],
        [ 3.9700,  2.5200,  3.3500,  5.3100,  6.4200,  3.1600,  0.0000,  6.3200],
        [10.0000,  5.8400,  8.6800,  6.1800,  6.6300,  9.5400, 17.3600,  0.0000],
        [ 2.0000,  9.6100,  7.1800,  8.9800,  3.4300,  0.3800,  0.0000,  0.7600],
        [ 2.5500,  7.8700,  5.2300,  3.4000,  8.9800,  7.4800,  0.0000, 14.9600],
        [ 2.8200,  5.4900,  6.7000,  4.7400,  3.1000,  9.5800,  0.0000, 19.1600],
        [ 4.9100,  8.2000,  0.6400,  0.4700,  9.0900,  9.6000,  1.2800,  0.0000],
        [ 2.8100,  4.2600,  1.8700,  9.2800,  5.7300,  1.8600,  0.0000,  3.7200],
        [10.0000,  5.6600,  4.9700,  0.5000,  1.5300,  4.2400,  9.9400,  0.0000],
        [ 6.7000, 10.0000,  2.5000,  0.8400,  6.5500,  9.3400,  5.0000,  0.0000],
        [ 2.6700,  0.6100,  8.8500,  6.0800,  4.2500,  9.4700,  

In [339]:
import torch.nn as nn
import torch.nn.functional as F

In [340]:
class SimpleClassifier(nn.Module):

    def __init__(self, n_inputs, n_hidden, n_outputs):
        super().__init__()
        # Initialize the modules we need to build the network
        self.linear1 = nn.Linear(n_inputs, n_hidden)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(n_hidden, n_outputs)

    def forward(self, x):
        # Perform the calculation of the model to determine the prediction
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        x = torch.sigmoid(x)
        return x

In [341]:
model = SimpleClassifier(n_inputs=8, n_hidden=32, n_outputs=3)
print(model)

SimpleClassifier(
  (linear1): Linear(in_features=8, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=3, bias=True)
)


In [342]:
for name, param in model.named_parameters():
    print(f"Parameter {name}, shape {param.shape}")

Parameter linear1.weight, shape torch.Size([32, 8])
Parameter linear1.bias, shape torch.Size([32])
Parameter linear2.weight, shape torch.Size([3, 32])
Parameter linear2.bias, shape torch.Size([3])


### Optimization

After defining the model and the dataset, it is time to prepare the optimization of the model. During training, we will perform the following steps:

1. Get a batch from the data loader
2. Obtain the predictions from the model for the batch
3. Calculate the loss based on the difference between predictions and labels
4. Backpropagation: calculate the gradients for every parameter with respect to the loss
5. Update the parameters of the model in the direction of the gradients

In [343]:
loss_fn = nn.BCELoss()

In [344]:
# Input to the optimizer are the parameters of the model: model.parameters()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [345]:
# Push model to device. Has to be only done once
device = 'cuda:0'
model.to(device)

SimpleClassifier(
  (linear1): Linear(in_features=8, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=3, bias=True)
)

In [346]:
def train_model(model, optimizer, train_loader, val_loader, loss_module, decision_threshold=0.5, num_epochs=100):

    best_validation_acc = 0

    for epoch in tqdm(range(num_epochs)):
        # training
        model.train()
        for train_input, train_labels in train_loader:

            ## Step 1: Move input data to device (only necessary if we use GPU)
            train_input = train_input.to(device)
            train_labels = train_labels.to(device)

            ## Step 2: Run the model on the input data
            train_preds = model(train_input)
            train_preds = train_preds.squeeze(dim=1) # Output is [Batch size, 1], but we want [Batch size]

            ## Step 3: Calculate the loss
            train_loss = loss_fn(train_preds, train_labels.float())

            ## Step 4: Perform backpropagation
            # Before calculating the gradients, we need to ensure that they are all zero.
            # The gradients would not be overwritten, but actually added to the existing ones.
            optimizer.zero_grad()
            # Perform backpropagation
            train_loss.backward()

            ## Step 5: Update the parameters
            optimizer.step()

        # validation
        model.eval()
        for val_input, val_labels in val_loader:
            val_losses = []
            n_correct_preds = 0
            n_all_preds = 0

            val_input = val_input.to(device)
            val_labels = val_labels.to(device)

            val_preds = model(val_input)
            class_preds = torch.argmax(val_preds, dim=1)
            val_loss = loss_fn(val_preds, val_labels.float())
            val_losses.append(val_loss.item())
            n_correct_preds += sum(class_preds==torch.argmax(val_labels, dim=1))
            n_all_preds += len(val_labels)

        current_acc = n_correct_preds / n_all_preds
        print(f'Average validation loss: {np.mean(val_losses)}')
        print(f'Average accuracy: {current_acc}')
        if current_acc > best_validation_acc:
            torch.save(model.state_dict(), "kset_model_Rev0.5.pth")
            print('Model weights saved')
            best_validation_acc = current_acc


In [347]:
train_model(model, optimizer, train_loader, val_loader, loss_fn, num_epochs=10)

  0%|          | 0/10 [00:00<?, ?it/s]

Average validation loss: 0.3993767499923706
Average accuracy: 0.8125
Model weights saved
Average validation loss: 0.361494779586792
Average accuracy: 0.875
Model weights saved
Average validation loss: 0.3425707221031189
Average accuracy: 0.875
Average validation loss: 0.3250531554222107
Average accuracy: 0.875
Average validation loss: 0.31572848558425903
Average accuracy: 0.8125
Average validation loss: 0.30314821004867554
Average accuracy: 0.875
Average validation loss: 0.2969340682029724
Average accuracy: 0.90625
Model weights saved
Average validation loss: 0.2863155007362366
Average accuracy: 0.90625
Average validation loss: 0.2763557732105255
Average accuracy: 0.84375
Average validation loss: 0.26850974559783936
Average accuracy: 0.90625


In [91]:
state_dictU = files.upload()

In [348]:
# Load state dict from the disk
state_dict = torch.load("kset_model_Rev0.5.pth")

# Create a new model and load the state
new_model = SimpleClassifier(n_inputs=8, n_hidden=32, n_outputs=3)
new_model.load_state_dict(state_dict)
new_model.to(device)

SimpleClassifier(
  (linear1): Linear(in_features=8, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=3, bias=True)
)

In [349]:
# upload csv file for prediction
upload = files.upload()

Saving NEW_TESZT_AutoCatalysis_parameters_Rev0.5.csv to NEW_TESZT_AutoCatalysis_parameters_Rev0.5.csv


In [350]:
#import pandas as pd
predict_df = pd.read_csv(list(upload.keys())[0], delimiter= ';')
predict_df

Type    k1    k2    k3    k4    k5    k6    k3r    k6r
0        1  6.37  5.09  3.15  1.93  1.32  0.22   6.30   0.00
1        3  9.56  9.92  8.95  5.84  2.20  4.91  17.90   0.00
2        3  6.98  2.08  0.73  3.43  5.00  1.12   1.46   0.00
3        3  3.06  2.57  0.78  2.84  5.81  1.39   1.56   0.00
4        3  2.10  1.75  3.76  1.43  1.88  1.02   7.52   0.00
...    ...   ...   ...   ...   ...   ...   ...    ...    ...
9897     2  1.30  3.86  8.07  4.69  6.08  9.86   0.00  19.72
9898     3  2.19  3.76  0.90  4.52  7.26  7.19   0.00  14.38
9899     2  1.83  9.84  2.38  9.57  8.90  5.25   0.00  10.50
9900     3  3.89  5.61  6.09  7.65  1.93  0.89   0.00   1.78
9901     2  0.51  7.16  1.08  1.70  3.36  9.36   0.00  18.72

[9902 rows x 9 columns]

In [351]:
predict_ds = KDataset(predict_df)
predict_ds[0]

(array([6.37, 5.09, 3.15, 1.93, 1.32, 0.22, 6.3 , 0.  ], dtype=float32),
 tensor([1, 0, 0]))

In [352]:
predictions = np.empty(len(predict_ds))
new_model.eval()

with torch.no_grad():
    for i, input in tqdm(enumerate(data.DataLoader(predict_ds, batch_size=1, shuffle=False)), total=len(predict_ds)):
        raw_predictions = new_model(input[0].to(device))
        predicted_type = torch.argmax(raw_predictions, dim=1) + 1
        predictions[i] = predicted_type

print(predictions)

  0%|          | 0/9902 [00:00<?, ?it/s]

[3. 3. 3. ... 2. 3. 2.]


In [353]:
predict_df.insert(1, "Predicted_Type", [p for p in predictions])
predict_df

Type  Predicted_Type    k1    k2    k3    k4    k5    k6    k3r    k6r
0        1             3.0  6.37  5.09  3.15  1.93  1.32  0.22   6.30   0.00
1        3             3.0  9.56  9.92  8.95  5.84  2.20  4.91  17.90   0.00
2        3             3.0  6.98  2.08  0.73  3.43  5.00  1.12   1.46   0.00
3        3             3.0  3.06  2.57  0.78  2.84  5.81  1.39   1.56   0.00
4        3             1.0  2.10  1.75  3.76  1.43  1.88  1.02   7.52   0.00
...    ...             ...   ...   ...   ...   ...   ...   ...    ...    ...
9897     2             2.0  1.30  3.86  8.07  4.69  6.08  9.86   0.00  19.72
9898     3             2.0  2.19  3.76  0.90  4.52  7.26  7.19   0.00  14.38
9899     2             2.0  1.83  9.84  2.38  9.57  8.90  5.25   0.00  10.50
9900     3             3.0  3.89  5.61  6.09  7.65  1.93  0.89   0.00   1.78
9901     2             2.0  0.51  7.16  1.08  1.70  3.36  9.36   0.00  18.72

[9902 rows x 10 columns]

In [354]:
pred_accuracy = sum(predict_df['Type'] == predict_df['Predicted_Type']) / len(predict_df['Type'])
pred_accuracy

0.7553019592001616

In [355]:
predict_df.to_csv('TESZT_AutoCatalysis_parameters_Rev0.5_with_prediction.csv', index=False, sep=';')