In [1]:
import numpy as np
import torch
import csv

from tqdm.notebook import tqdm

In [2]:
torch.cuda.is_available()

True

In [3]:
from google.colab import files
uploaded_file = files.upload()

Saving NEW_TANULO_AutoCatalysis_parameters_None.csv to NEW_TANULO_AutoCatalysis_parameters_None.csv


In [4]:
list(uploaded_file.keys())[0]

'NEW_TANULO_AutoCatalysis_parameters_None.csv'

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv(list(uploaded_file.keys())[0], delimiter= ';')
df

Type    k1     k2    k3    k4    k5    k6  kon1  kon2  kcat  k1r  k2r  \
0        1  5.40   5.05  6.03  4.17  7.98  5.97     0     0     0    0    0   
1        1  8.80   4.30  1.36  8.25  4.37  6.36     0     0     0    0    0   
2        1  7.01   8.66  4.77  3.71  9.89  9.32     0     0     0    0    0   
3        1  6.75   6.76  5.28  1.78  8.44  2.24     0     0     0    0    0   
4        1  6.42   9.33  4.00  2.69  1.77  7.13     0     0     0    0    0   
...    ...   ...    ...   ...   ...   ...   ...   ...   ...   ...  ...  ...   
2695     2  2.27   2.25  8.25  5.17  5.17  6.46     0     0     0    0    0   
2696     2  1.95  10.00  2.27  5.37  4.62  3.83     0     0     0    0    0   
2697     2  7.59   8.00  0.36  9.02  6.76  1.88     0     0     0    0    0   
2698     2  2.93   4.55  0.17  3.10  8.81  4.87     0     0     0    0    0   
2699     2  7.91   2.94  1.65  8.78  2.35  2.75     0     0     0    0    0   

      k3r  k4r  k5r  k6r  koff1  koff2  kcatr  
0       0    0    0    0      0      0      0  
1       0    0    0    0      0      0      0  
2       0    0    0    0      0      0      0  
3       0    0    0    0      0      0      0  
4       0    0    0    0      0      0      0  
...   ...  ...  ...  ...    ...    ...    ...  
2695    0    0    0    0      0      0      0  
2696    0    0    0    0      0      0      0  
2697    0    0    0    0      0      0      0  
2698    0    0    0    0      0      0      0  
2699    0    0    0    0      0      0      0  

[2700 rows x 19 columns]

In [6]:
train_df, val_df = train_test_split(df, test_size=0.2)

In [7]:
val_df

Type    k1     k2    k3    k4    k5    k6  kon1  kon2  kcat  k1r  k2r  \
1963     2  0.98   1.72  2.05  4.98  1.09  4.00     0     0     0    0    0   
2136     2  0.33  10.00  8.99  3.56  8.55  5.84     0     0     0    0    0   
1371     2  0.14   2.30  0.33  1.68  6.90  8.46     0     0     0    0    0   
1178     1  9.45   8.80  8.33  4.45  5.04  8.24     0     0     0    0    0   
1870     2  0.86   1.94  3.91  1.66  6.73  6.68     0     0     0    0    0   
...    ...   ...    ...   ...   ...   ...   ...   ...   ...   ...  ...  ...   
834      1  8.04   4.58  7.65  5.29  0.60  0.33     0     0     0    0    0   
147      1  7.09   2.92  5.73  0.73  0.41  2.33     0     0     0    0    0   
2059     2  3.37   0.30  4.13  3.76  9.85  5.04     0     0     0    0    0   
494      1  8.46   2.38  8.84  6.04  7.10  4.63     0     0     0    0    0   
303      1  9.05   9.44  1.88  5.70  7.20  8.20     0     0     0    0    0   

      k3r  k4r  k5r  k6r  koff1  koff2  kcatr  
1963    0    0    0    0      0      0      0  
2136    0    0    0    0      0      0      0  
1371    0    0    0    0      0      0      0  
1178    0    0    0    0      0      0      0  
1870    0    0    0    0      0      0      0  
...   ...  ...  ...  ...    ...    ...    ...  
834     0    0    0    0      0      0      0  
147     0    0    0    0      0      0      0  
2059    0    0    0    0      0      0      0  
494     0    0    0    0      0      0      0  
303     0    0    0    0      0      0      0  

[540 rows x 19 columns]

In [8]:
train_df

Type     k1    k2     k3    k4    k5     k6  kon1  kon2  kcat  k1r  k2r  \
33       1   8.32  7.20   4.43  7.79  9.29   0.86     0     0     0    0    0   
2021     2   2.70  9.38   3.19  6.69  2.84   6.12     0     0     0    0    0   
1810     2   3.41  4.58   1.40  3.90  7.66   5.90     0     0     0    0    0   
1382     2   2.32  6.65   5.25  7.53  2.58   8.94     0     0     0    0    0   
2586     2   2.01  6.46   6.79  4.50  5.54   3.86     0     0     0    0    0   
...    ...    ...   ...    ...   ...   ...    ...   ...   ...   ...  ...  ...   
252      1   7.46  3.21   5.44  4.18  2.06   9.19     0     0     0    0    0   
1896     2   6.51  1.97   2.70  8.84  6.91   7.71     0     0     0    0    0   
1224     1   1.51  5.13   4.78  1.34  8.23  10.00     0     0     0    0    0   
2049     2   5.71  6.92  10.00  6.80  1.21   9.05     0     0     0    0    0   
51       1  10.00  6.98   7.50  5.53  6.73   5.63     0     0     0    0    0   

      k3r  k4r  k5r  k6r  koff1  koff2  kcatr  
33      0    0    0    0      0      0      0  
2021    0    0    0    0      0      0      0  
1810    0    0    0    0      0      0      0  
1382    0    0    0    0      0      0      0  
2586    0    0    0    0      0      0      0  
...   ...  ...  ...  ...    ...    ...    ...  
252     0    0    0    0      0      0      0  
1896    0    0    0    0      0      0      0  
1224    0    0    0    0      0      0      0  
2049    0    0    0    0      0      0      0  
51      0    0    0    0      0      0      0  

[2160 rows x 19 columns]

In [9]:
train_df.values

array([[ 1.  ,  8.32,  7.2 , ...,  0.  ,  0.  ,  0.  ],
       [ 2.  ,  2.7 ,  9.38, ...,  0.  ,  0.  ,  0.  ],
       [ 2.  ,  3.41,  4.58, ...,  0.  ,  0.  ,  0.  ],
       ...,
       [ 1.  ,  1.51,  5.13, ...,  0.  ,  0.  ,  0.  ],
       [ 2.  ,  5.71,  6.92, ...,  0.  ,  0.  ,  0.  ],
       [ 1.  , 10.  ,  6.98, ...,  0.  ,  0.  ,  0.  ]])

In [10]:
torch.Tensor(train_df.values)[:,1:7]

tensor([[ 8.3200,  7.2000,  4.4300,  7.7900,  9.2900,  0.8600],
        [ 2.7000,  9.3800,  3.1900,  6.6900,  2.8400,  6.1200],
        [ 3.4100,  4.5800,  1.4000,  3.9000,  7.6600,  5.9000],
        ...,
        [ 1.5100,  5.1300,  4.7800,  1.3400,  8.2300, 10.0000],
        [ 5.7100,  6.9200, 10.0000,  6.8000,  1.2100,  9.0500],
        [10.0000,  6.9800,  7.5000,  5.5300,  6.7300,  5.6300]])

In [11]:
himport torch.utils.data as data
class KDataset(data.Dataset):

    def __init__(self, df, n_labels=2):
        """
        Inputs:
            df - pandas dataframe containing the data
        """
        super().__init__()
        self.n_labels = n_labels
        self.data = df
        self.ks = df.values[:, 1:7].astype(np.float32)
        self.labels = df.values[:, 0].astype(int)-1

    def __len__(self):
        # Number of data points
        return len(self.data)

    def __getitem__(self, i):
        # Return the i-th data point of the dataset
        k_values = self.ks[i]
        label = self.labels[i]
        labels = torch.tensor([1 if i==label else 0 for i in range(self.n_labels)])
        return k_values, labels

In [12]:
train_ds = KDataset(train_df)
print("Size of dataset:", len(train_ds))
print("Data point 0:", train_ds[0])

Size of dataset: 2160
Data point 0: (array([8.32, 7.2 , 4.43, 7.79, 9.29, 0.86], dtype=float32), tensor([1, 0]))


In [13]:
val_ds = KDataset(val_df)
print("Size of dataset:", len(val_ds))
print("Data point 0:", val_ds[0])

Size of dataset: 540
Data point 0: (array([0.98, 1.72, 2.05, 4.98, 1.09, 4.  ], dtype=float32), tensor([0, 1]))


In [14]:
train_loader = data.DataLoader(train_ds, batch_size=32, shuffle=True, drop_last=True)
val_loader = data.DataLoader(val_ds, batch_size=32, shuffle=False, drop_last=True)

In [15]:
data_inputs, data_labels = next(iter(train_loader))

# The shape of the outputs are [batch_size, d_1,...,d_N] where d_1,...,d_N are the
# dimensions of the data point returned from the dataset class
print("Data inputs", data_inputs.shape, "\n", data_inputs)
print("Data labels", data_labels.shape, "\n", data_labels)

Data inputs torch.Size([32, 6]) 
 tensor([[ 2.2000,  2.5300,  1.5400,  8.9300,  7.2100,  7.8500],
        [ 0.1900,  1.3200,  1.6500,  5.0800,  0.5700,  6.5100],
        [ 5.8800,  9.1300,  2.1900,  1.9800,  0.6200,  4.0300],
        [ 2.3500,  5.9600,  5.7800,  4.8900,  7.0600,  2.3200],
        [ 9.6200,  9.1700,  5.8600,  6.8100,  4.3500,  3.4800],
        [ 0.6400,  8.2000,  7.9000,  3.4500,  9.6400,  0.4800],
        [ 4.6200,  7.4100,  2.2700,  4.8100,  9.8100,  8.9000],
        [ 8.7400,  3.9400,  6.1900,  8.2100,  4.8700,  7.5300],
        [ 1.8800,  6.8800,  5.6600,  3.3300,  1.7700,  6.7700],
        [ 1.4600,  7.4400,  3.7600,  5.3200,  8.0000,  3.5000],
        [ 4.6100,  0.5200,  5.4300,  8.2800,  5.0500,  8.4700],
        [ 2.4100,  9.6200,  7.3600,  7.6800,  0.4400,  6.4700],
        [ 3.0600,  6.0500,  4.3500,  6.8700,  0.3000,  7.7200],
        [ 9.7900,  7.6100,  1.0200,  6.4300,  5.5200,  0.7900],
        [ 7.2000,  6.2700,  2.4100,  4.9400,  3.4700,  4.5500],
      

In [16]:
import torch.nn as nn
import torch.nn.functional as F

In [17]:
class SimpleClassifier(nn.Module):

    def __init__(self, n_inputs, n_hidden, n_outputs):
        super().__init__()
        # Initialize the modules we need to build the network
        self.linear1 = nn.Linear(n_inputs, n_hidden)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(n_hidden, n_outputs)

    def forward(self, x):
        # Perform the calculation of the model to determine the prediction
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        x = torch.sigmoid(x)
        return x

In [18]:
model = SimpleClassifier(n_inputs=6, n_hidden=32, n_outputs=2)
print(model)

SimpleClassifier(
  (linear1): Linear(in_features=6, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=2, bias=True)
)


In [19]:
for name, param in model.named_parameters():
    print(f"Parameter {name}, shape {param.shape}")

Parameter linear1.weight, shape torch.Size([32, 6])
Parameter linear1.bias, shape torch.Size([32])
Parameter linear2.weight, shape torch.Size([2, 32])
Parameter linear2.bias, shape torch.Size([2])


### Optimization

After defining the model and the dataset, it is time to prepare the optimization of the model. During training, we will perform the following steps:

1. Get a batch from the data loader
2. Obtain the predictions from the model for the batch
3. Calculate the loss based on the difference between predictions and labels
4. Backpropagation: calculate the gradients for every parameter with respect to the loss
5. Update the parameters of the model in the direction of the gradients

In [20]:
loss_fn = nn.BCELoss()

In [21]:
# Input to the optimizer are the parameters of the model: model.parameters()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [22]:
# Push model to device. Has to be only done once
device = 'cuda:0'
model.to(device)

SimpleClassifier(
  (linear1): Linear(in_features=6, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=2, bias=True)
)

In [23]:
def train_model(model, optimizer, train_loader, val_loader, loss_module, decision_threshold=0.5, num_epochs=100):

    best_validation_acc = 0

    for epoch in tqdm(range(num_epochs)):
        # training
        model.train()
        for train_input, train_labels in train_loader:

            ## Step 1: Move input data to device (only necessary if we use GPU)
            train_input = train_input.to(device)
            train_labels = train_labels.to(device)

            ## Step 2: Run the model on the input data
            train_preds = model(train_input)
            train_preds = train_preds.squeeze(dim=1) # Output is [Batch size, 1], but we want [Batch size]

            ## Step 3: Calculate the loss
            train_loss = loss_fn(train_preds, train_labels.float())

            ## Step 4: Perform backpropagation
            # Before calculating the gradients, we need to ensure that they are all zero.
            # The gradients would not be overwritten, but actually added to the existing ones.
            optimizer.zero_grad()
            # Perform backpropagation
            train_loss.backward()

            ## Step 5: Update the parameters
            optimizer.step()

        # validation
        model.eval()
        for val_input, val_labels in val_loader:
            val_losses = []
            n_correct_preds = 0
            n_all_preds = 0

            val_input = val_input.to(device)
            val_labels = val_labels.to(device)

            val_preds = model(val_input)
            class_preds = torch.argmax(val_preds, dim=1)
            val_loss = loss_fn(val_preds, val_labels.float())
            val_losses.append(val_loss.item())
            n_correct_preds += sum(class_preds==torch.argmax(val_labels, dim=1))
            n_all_preds += len(val_labels)

        current_acc = n_correct_preds / n_all_preds
        print(f'Average validation loss: {np.mean(val_losses)}')
        print(f'Average accuracy: {current_acc}')
        if current_acc > best_validation_acc:
            torch.save(model.state_dict(), "kset_model_None.pth")
            print('Model weights saved')
            best_validation_acc = current_acc


In [24]:
train_model(model, optimizer, train_loader, val_loader, loss_fn, num_epochs=10)

  0%|          | 0/10 [00:00<?, ?it/s]

Average validation loss: 0.4913192391395569
Average accuracy: 0.90625
Model weights saved
Average validation loss: 0.3667372465133667
Average accuracy: 0.90625
Average validation loss: 0.2962492108345032
Average accuracy: 0.9375
Model weights saved
Average validation loss: 0.2603318989276886
Average accuracy: 0.9375
Average validation loss: 0.22917017340660095
Average accuracy: 0.96875
Model weights saved
Average validation loss: 0.209552600979805
Average accuracy: 0.96875
Average validation loss: 0.19642391800880432
Average accuracy: 0.96875
Average validation loss: 0.18729186058044434
Average accuracy: 0.96875
Average validation loss: 0.17586907744407654
Average accuracy: 0.9375
Average validation loss: 0.16705994307994843
Average accuracy: 0.96875


In [25]:
# Load state dict from the disk
state_dict = torch.load("kset_model_None.pth")
#from google.colab import files
#state_dict = files.upload()

# Create a new model and load the state
new_model = SimpleClassifier(n_inputs=6, n_hidden=32, n_outputs=2)
new_model.load_state_dict(state_dict)
new_model.to(device)

SimpleClassifier(
  (linear1): Linear(in_features=6, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=2, bias=True)
)

In [26]:
# upload csv file for prediction
upload = files.upload()

Saving NEW_TESZT_AutoCatalysis_parameters_None.csv to NEW_TESZT_AutoCatalysis_parameters_None.csv


In [27]:
predict_df = pd.read_csv(list(upload.keys())[0], delimiter= ';')
predict_df

Type    k1    k2    k3    k4    k5    k6  kon1  kon2  kcat  k1r  k2r  \
0        1  6.37  5.09  3.15  1.93  1.32  0.22     0     0     0    0    0   
1        1  9.56  9.92  8.95  5.84  2.20  4.91     0     0     0    0    0   
2        1  6.98  2.08  0.73  3.43  5.00  1.12     0     0     0    0    0   
3        1  3.06  2.57  0.78  2.84  5.81  1.39     0     0     0    0    0   
4        1  2.10  1.75  3.76  1.43  1.88  1.02     0     0     0    0    0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...  ...   
9939     2  1.30  3.86  8.07  4.69  6.08  9.86     0     0     0    0    0   
9940     2  2.19  3.76  0.90  4.52  7.26  7.19     0     0     0    0    0   
9941     2  1.83  9.84  2.38  9.57  8.90  5.25     0     0     0    0    0   
9942     2  3.89  5.61  6.09  7.65  1.93  0.89     0     0     0    0    0   
9943     2  0.51  7.16  1.08  1.70  3.36  9.36     0     0     0    0    0   

      k3r  k4r  k5r  k6r  koff1  koff2  kcatr  
0       0    0    0    0      0      0      0  
1       0    0    0    0      0      0      0  
2       0    0    0    0      0      0      0  
3       0    0    0    0      0      0      0  
4       0    0    0    0      0      0      0  
...   ...  ...  ...  ...    ...    ...    ...  
9939    0    0    0    0      0      0      0  
9940    0    0    0    0      0      0      0  
9941    0    0    0    0      0      0      0  
9942    0    0    0    0      0      0      0  
9943    0    0    0    0      0      0      0  

[9944 rows x 19 columns]

In [28]:
predict_ds = KDataset(predict_df)
predict_ds[0]

(array([6.37, 5.09, 3.15, 1.93, 1.32, 0.22], dtype=float32), tensor([1, 0]))

In [29]:
predictions = np.empty(len(predict_ds))
new_model.eval()

with torch.no_grad():
    for i, input in tqdm(enumerate(data.DataLoader(predict_ds, batch_size=1, shuffle=False)), total=len(predict_ds)):
        raw_predictions = new_model(input[0].to(device))
        predicted_type = torch.argmax(raw_predictions, dim=1) + 1
        predictions[i] = predicted_type

print(predictions)

  0%|          | 0/9944 [00:00<?, ?it/s]

[1. 1. 1. ... 2. 2. 2.]


In [30]:
predict_df.insert(1, "Predicted_Type", [p for p in predictions])
predict_df

Type  Predicted_Type    k1    k2    k3    k4    k5    k6  kon1  kon2  \
0        1             1.0  6.37  5.09  3.15  1.93  1.32  0.22     0     0   
1        1             1.0  9.56  9.92  8.95  5.84  2.20  4.91     0     0   
2        1             1.0  6.98  2.08  0.73  3.43  5.00  1.12     0     0   
3        1             1.0  3.06  2.57  0.78  2.84  5.81  1.39     0     0   
4        1             1.0  2.10  1.75  3.76  1.43  1.88  1.02     0     0   
...    ...             ...   ...   ...   ...   ...   ...   ...   ...   ...   
9939     2             2.0  1.30  3.86  8.07  4.69  6.08  9.86     0     0   
9940     2             2.0  2.19  3.76  0.90  4.52  7.26  7.19     0     0   
9941     2             2.0  1.83  9.84  2.38  9.57  8.90  5.25     0     0   
9942     2             2.0  3.89  5.61  6.09  7.65  1.93  0.89     0     0   
9943     2             2.0  0.51  7.16  1.08  1.70  3.36  9.36     0     0   

      kcat  k1r  k2r  k3r  k4r  k5r  k6r  koff1  koff2  kcatr  
0        0    0    0    0    0    0    0      0      0      0  
1        0    0    0    0    0    0    0      0      0      0  
2        0    0    0    0    0    0    0      0      0      0  
3        0    0    0    0    0    0    0      0      0      0  
4        0    0    0    0    0    0    0      0      0      0  
...    ...  ...  ...  ...  ...  ...  ...    ...    ...    ...  
9939     0    0    0    0    0    0    0      0      0      0  
9940     0    0    0    0    0    0    0      0      0      0  
9941     0    0    0    0    0    0    0      0      0      0  
9942     0    0    0    0    0    0    0      0      0      0  
9943     0    0    0    0    0    0    0      0      0      0  

[9944 rows x 20 columns]

In [32]:
pred_accuracy = sum(predict_df['Type'] == predict_df['Predicted_Type']) / len(predict_df['Type'])
pred_accuracy

0.9742558326629123

In [34]:
predict_df.to_csv('TESZT_AutCatalysis_parameters_None_with_prediction.csv', index=False, sep=';')