In [57]:
import numpy as np
import torch
import csv

from tqdm.notebook import tqdm

In [58]:
torch.cuda.is_available()

True

In [91]:
from google.colab import files

In [92]:
from google.colab import files
uploaded_file = files.upload()

Saving NEW_TANULO_AutoCatalysis_parameters_HetCat2.csv to NEW_TANULO_AutoCatalysis_parameters_HetCat2.csv


In [93]:
list(uploaded_file.keys())[0]

'NEW_TANULO_AutoCatalysis_parameters_HetCat2.csv'

In [94]:
import pandas as pd
from sklearn.model_selection import train_test_split


In [95]:
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv(list(uploaded_file.keys())[0], delimiter= ';')
df

Type    k1    k2    k3    k4    k5    k6  NumOfEQ  E1kon1  E1kon2  ...  \
0        1  4.57  5.69  4.69  1.58  1.74  9.01        4    0.00    0.00  ...   
1        1  7.55  8.50  0.34  1.42  8.67  8.64        4    0.00    0.00  ...   
2        1  9.70  5.50  8.82  1.08  9.52  6.45        4    0.00    0.00  ...   
3        1  7.05  9.17  4.25  5.46  6.52  3.50        4    0.00    0.00  ...   
4        1  8.94  4.84  4.66  0.77  3.02  3.10        4    0.00    0.00  ...   
...    ...   ...   ...   ...   ...   ...   ...      ...     ...     ...  ...   
2695     3  8.02  8.90  8.33  9.80  6.95  5.11        1    0.00    0.00  ...   
2696     3  3.20  5.69  1.14  3.51  9.89  1.16        1    0.00    0.00  ...   
2697     3  2.24  7.19  9.27  0.15  9.16  3.13        4    3.23    8.45  ...   
2698     3  3.81  6.77  4.85  3.36  8.06  1.46        4    9.60    5.10  ...   
2699     3  2.54  5.27  9.55  1.74  7.97  2.32        4    9.84    5.79  ...   

      E5kon1  E5kon2  E5kcat  E5koff1  E5koff2  E6kon1  E6kon2  E6kcat  \
0        0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
1        0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
2        0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
3        0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
4        0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
...      ...     ...     ...      ...      ...     ...     ...     ...   
2695     0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
2696     0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
2697     0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
2698     0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   
2699     0.0     0.0     0.0      0.0      0.0     0.0     0.0     0.0   

      E6koff1  E6koff2  
0         0.0      0.0  
1         0.0      0.0  
2         0.0      0.0  
3         0.0      0.0  
4         0.0      0.0  
...       ...      ...  
2695      0.0      0.0  
2696      0.0      0.0  
2697      0.0      0.0  
2698      0.0      0.0  
2699      0.0      0.0  

[2700 rows x 38 columns]

In [96]:
train_df, val_df = train_test_split(df, test_size=0.2)

In [97]:
val_df

Type    k1    k2    k3    k4    k5     k6  NumOfEQ  E1kon1  E1kon2  ...  \
115      1  9.47  8.21  4.89  4.32  6.99   1.56        4    0.00    0.00  ...   
2034     3  1.77  7.37  6.60  1.84  9.46   6.32        1    0.00    0.00  ...   
2050     3  1.40  2.48  8.64  2.82  6.86  10.00        1    0.00    0.00  ...   
388      1  3.33  4.53  7.35  2.93  5.65   0.20        4    0.00    0.00  ...   
2499     3  2.33  5.31  4.89  1.41  2.47   1.24        4    6.74    2.84  ...   
...    ...   ...   ...   ...   ...   ...    ...      ...     ...     ...  ...   
1771     2  5.39  6.32  8.53  6.70  1.21   7.80        1    0.00    0.00  ...   
1842     3  5.06  9.39  0.39  1.81  0.44   7.03        4   10.00    1.84  ...   
1663     2  0.60  2.03  2.25  5.90  5.88   7.91        1    0.00    0.00  ...   
2460     3  0.57  6.68  7.39  9.49  3.07   7.87        1    0.00    0.00  ...   
119      1  7.00  6.74  9.36  6.07  1.05   3.99        4    0.00    0.00  ...   

      E5kon1  E5kon2  E5kcat  E5koff1  E5koff2  E6kon1  E6kon2  E6kcat  \
115     0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
2034    0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
2050    0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
388     0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
2499    0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
...      ...     ...     ...      ...      ...     ...     ...     ...   
1771    5.66    9.78    8.87     0.89     1.17    0.00    0.00    0.00   
1842    0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
1663    0.00    0.00    0.00     0.00     0.00    5.84    6.38    6.72   
2460    0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
119     0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   

      E6koff1  E6koff2  
115      0.00     0.00  
2034     0.00     0.00  
2050     0.00     0.00  
388      0.00     0.00  
2499     0.00     0.00  
...       ...      ...  
1771     0.00     0.00  
1842     0.00     0.00  
1663     0.98     0.88  
2460     0.00     0.00  
119      0.00     0.00  

[540 rows x 38 columns]

In [98]:
train_df

Type    k1    k2    k3    k4     k5    k6  NumOfEQ  E1kon1  E1kon2  ...  \
26       1  9.73  3.77  6.71  3.96   2.80  5.81        4     0.0     0.0  ...   
13       1  6.72  4.95  3.00  6.03   4.69  6.85        4     0.0     0.0  ...   
780      1  9.25  1.23  5.77  3.62  10.00  2.39        4     0.0     0.0  ...   
2192     3  5.12  8.92  6.08  6.57   1.76  4.85        1     0.0     0.0  ...   
579      1  2.62  8.84  4.06  0.54   3.53  6.72        4     0.0     0.0  ...   
...    ...   ...   ...   ...   ...    ...   ...      ...     ...     ...  ...   
1599     2  5.72  4.16  6.03  6.85   3.65  8.93        1     0.0     0.0  ...   
941      2  5.17  8.09  1.52  7.72   2.23  1.81        1     0.0     0.0  ...   
306      1  8.07  1.75  0.19  2.48   4.66  6.70        4     0.0     0.0  ...   
326      1  3.65  8.84  9.61  1.03   1.30  6.43        4     0.0     0.0  ...   
184      1  6.64  7.81  9.41  0.75   8.32  6.74        4     0.0     0.0  ...   

      E5kon1  E5kon2  E5kcat  E5koff1  E5koff2  E6kon1  E6kon2  E6kcat  \
26      0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
13      0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
780     0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
2192    0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
579     0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
...      ...     ...     ...      ...      ...     ...     ...     ...   
1599    0.00    0.00    0.00     0.00     0.00    9.13    1.39    8.96   
941     6.09    5.85    0.19     1.77     0.76    0.00    0.00    0.00   
306     0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
326     0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
184     0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   

      E6koff1  E6koff2  
26       0.00     0.00  
13       0.00     0.00  
780      0.00     0.00  
2192     0.00     0.00  
579      0.00     0.00  
...       ...      ...  
1599     1.08     0.29  
941      0.00     0.00  
306      0.00     0.00  
326      0.00     0.00  
184      0.00     0.00  

[2160 rows x 38 columns]

In [99]:
train_df.values

array([[1.  , 9.73, 3.77, ..., 0.  , 0.  , 0.  ],
       [1.  , 6.72, 4.95, ..., 0.  , 0.  , 0.  ],
       [1.  , 9.25, 1.23, ..., 0.  , 0.  , 0.  ],
       ...,
       [1.  , 8.07, 1.75, ..., 0.  , 0.  , 0.  ],
       [1.  , 3.65, 8.84, ..., 0.  , 0.  , 0.  ],
       [1.  , 6.64, 7.81, ..., 0.  , 0.  , 0.  ]])

In [100]:
torch.Tensor(train_df.values)[:,1:38]

tensor([[9.7300, 3.7700, 6.7100,  ..., 0.0000, 0.0000, 0.0000],
        [6.7200, 4.9500, 3.0000,  ..., 0.0000, 0.0000, 0.0000],
        [9.2500, 1.2300, 5.7700,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [8.0700, 1.7500, 0.1900,  ..., 0.0000, 0.0000, 0.0000],
        [3.6500, 8.8400, 9.6100,  ..., 0.0000, 0.0000, 0.0000],
        [6.6400, 7.8100, 9.4100,  ..., 0.0000, 0.0000, 0.0000]])

In [101]:
import torch.utils.data as data
class KDataset(data.Dataset):

    def __init__(self, df, n_labels=3):
        """
        Inputs:
            df - pandas dataframe containing the data
        """
        super().__init__()
        self.n_labels = n_labels
        self.data = df
        self.ks = df.values[:, 1:38].astype(np.float32)
        self.labels = df.values[:, 0].astype(int)-1

    def __len__(self):
        # Number of data points
        return len(self.data)

    def __getitem__(self, i):
        # Return the i-th data point of the dataset
        k_values = self.ks[i]
        label = self.labels[i]
        labels = torch.tensor([1 if i==label else 0 for i in range(self.n_labels)])
        return k_values, labels

In [102]:
train_ds = KDataset(train_df)
print("Size of dataset:", len(train_ds))
print("Data point 0:", train_ds[0])

Size of dataset: 2160
Data point 0: (array([9.73, 3.77, 6.71, 3.96, 2.8 , 5.81, 4.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 7.32, 8.65, 9.67, 2.06, 2.17,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  ], dtype=float32), tensor([1, 0, 0]))


In [103]:
val_ds = KDataset(val_df)
print("Size of dataset:", len(val_ds))
print("Data point 0:", val_ds[0])

Size of dataset: 540
Data point 0: (array([9.47, 8.21, 4.89, 4.32, 6.99, 1.56, 4.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 2.22, 3.77, 8.32, 1.09, 0.72,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  ], dtype=float32), tensor([1, 0, 0]))


In [104]:
train_loader = data.DataLoader(train_ds, batch_size=32, shuffle=True, drop_last=True)
val_loader = data.DataLoader(val_ds, batch_size=32, shuffle=False, drop_last=True)

In [105]:
data_inputs, data_labels = next(iter(train_loader))

# The shape of the outputs are [batch_size, d_1,...,d_N] where d_1,...,d_N are the
# dimensions of the data point returned from the dataset class
print("Data inputs", data_inputs.shape, "\n", data_inputs)
print("Data labels", data_labels.shape, "\n", data_labels)

Data inputs torch.Size([32, 37]) 
 tensor([[ 1.3200,  8.4600,  7.5500,  ...,  0.0000,  0.0000,  0.0000],
        [ 3.3400,  8.4800,  9.3000,  ...,  0.0000,  0.0000,  0.0000],
        [10.0000,  7.6400,  5.6900,  ...,  0.0000,  0.0000,  0.0000],
        ...,
        [ 7.8800,  8.2100,  0.1500,  ...,  0.0000,  0.0000,  0.0000],
        [ 6.1600,  0.5800,  4.6700,  ...,  0.0000,  0.0000,  0.0000],
        [ 4.9000,  9.6200,  7.5600,  ...,  1.7800,  0.0400,  1.2100]])
Data labels torch.Size([32, 3]) 
 tensor([[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
        [1, 0, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
        [0, 1, 0],
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0],
   

In [106]:
import torch.nn as nn
import torch.nn.functional as F

In [107]:
class SimpleClassifier(nn.Module):

    def __init__(self, n_inputs, n_hidden, n_outputs):
        super().__init__()
        # Initialize the modules we need to build the network
        self.linear1 = nn.Linear(n_inputs, n_hidden)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(n_hidden, n_outputs)

    def forward(self, x):
        # Perform the calculation of the model to determine the prediction
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        x = torch.sigmoid(x)
        return x

In [108]:
model = SimpleClassifier(n_inputs=37, n_hidden=32, n_outputs=3)
print(model)

SimpleClassifier(
  (linear1): Linear(in_features=37, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=3, bias=True)
)


In [109]:
for name, param in model.named_parameters():
    print(f"Parameter {name}, shape {param.shape}")

Parameter linear1.weight, shape torch.Size([32, 37])
Parameter linear1.bias, shape torch.Size([32])
Parameter linear2.weight, shape torch.Size([3, 32])
Parameter linear2.bias, shape torch.Size([3])


### Optimization

After defining the model and the dataset, it is time to prepare the optimization of the model. During training, we will perform the following steps:

1. Get a batch from the data loader
2. Obtain the predictions from the model for the batch
3. Calculate the loss based on the difference between predictions and labels
4. Backpropagation: calculate the gradients for every parameter with respect to the loss
5. Update the parameters of the model in the direction of the gradients

In [110]:
loss_fn = nn.BCELoss()

In [111]:
# Input to the optimizer are the parameters of the model: model.parameters()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [112]:
# Push model to device. Has to be only done once
device = 'cuda:0'
model.to(device)

SimpleClassifier(
  (linear1): Linear(in_features=37, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=3, bias=True)
)

In [113]:
def train_model(model, optimizer, train_loader, val_loader, loss_module, decision_threshold=0.5, num_epochs=100):

    best_validation_acc = 0

    for epoch in tqdm(range(num_epochs)):
        # training
        model.train()
        for train_input, train_labels in train_loader:

            ## Step 1: Move input data to device (only necessary if we use GPU)
            train_input = train_input.to(device)
            train_labels = train_labels.to(device)

            ## Step 2: Run the model on the input data
            train_preds = model(train_input)
            train_preds = train_preds.squeeze(dim=1) # Output is [Batch size, 1], but we want [Batch size]

            ## Step 3: Calculate the loss
            train_loss = loss_fn(train_preds, train_labels.float())

            ## Step 4: Perform backpropagation
            # Before calculating the gradients, we need to ensure that they are all zero.
            # The gradients would not be overwritten, but actually added to the existing ones.
            optimizer.zero_grad()
            # Perform backpropagation
            train_loss.backward()

            ## Step 5: Update the parameters
            optimizer.step()

        # validation
        model.eval()
        for val_input, val_labels in val_loader:
            val_losses = []
            n_correct_preds = 0
            n_all_preds = 0

            val_input = val_input.to(device)
            val_labels = val_labels.to(device)

            val_preds = model(val_input)
            class_preds = torch.argmax(val_preds, dim=1)
            val_loss = loss_fn(val_preds, val_labels.float())
            val_losses.append(val_loss.item())
            n_correct_preds += sum(class_preds==torch.argmax(val_labels, dim=1))
            n_all_preds += len(val_labels)

        current_acc = n_correct_preds / n_all_preds
        print(f'Average validation loss: {np.mean(val_losses)}')
        print(f'Average accuracy: {current_acc}')
        if current_acc > best_validation_acc:
            torch.save(model.state_dict(), "kset_model_HetCat2_NEW.pth")
            print('Model weights saved')
            best_validation_acc = current_acc


In [114]:
train_model(model, optimizer, train_loader, val_loader, loss_fn, num_epochs=10)

  0%|          | 0/10 [00:00<?, ?it/s]

Average validation loss: 0.4969307780265808
Average accuracy: 0.78125
Model weights saved
Average validation loss: 0.3664091229438782
Average accuracy: 0.96875
Model weights saved
Average validation loss: 0.266198992729187
Average accuracy: 0.96875
Average validation loss: 0.20131759345531464
Average accuracy: 0.96875
Average validation loss: 0.15953268110752106
Average accuracy: 0.96875
Average validation loss: 0.1352933943271637
Average accuracy: 0.96875
Average validation loss: 0.12042023241519928
Average accuracy: 0.96875
Average validation loss: 0.11274558305740356
Average accuracy: 0.96875
Average validation loss: 0.10555335134267807
Average accuracy: 0.96875
Average validation loss: 0.10114368796348572
Average accuracy: 0.96875


In [ ]:
state_dictU = files.upload()

Saving kset_model_HetCat2.pth to kset_model_HetCat2.pth


In [115]:
# Load state dict from the disk
#state_dict = files.upload()
state_dict = torch.load("kset_model_HetCat2_NEW.pth")

# Create a new model and load the state
new_model = SimpleClassifier(n_inputs=37, n_hidden=32, n_outputs=3)
new_model.load_state_dict(state_dict)
new_model.to(device)

SimpleClassifier(
  (linear1): Linear(in_features=37, out_features=32, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=32, out_features=3, bias=True)
)

In [116]:
# upload csv file for prediction
upload = files.upload()

Saving NEW_TESZT_AutoCatalysis_parameters_HetCat2.csv to NEW_TESZT_AutoCatalysis_parameters_HetCat2.csv


In [117]:
#import pandas as pd
predict_df = pd.read_csv(list(upload.keys())[0], delimiter= ';')
predict_df

Type    k1    k2    k3     k4    k5    k6  NumOfEQ  E1kon1  E1kon2  ...  \
0        1  6.37  5.09  3.15   1.93  1.32  0.22        4     0.0     0.0  ...   
1        1  9.56  9.92  8.95   5.84  2.20  4.91        4     0.0     0.0  ...   
2        1  2.34  6.50  5.09   0.87  7.58  4.48        4     0.0     0.0  ...   
3        1  9.31  3.83  5.20   2.74  6.26  5.36        4     0.0     0.0  ...   
4        1  9.32  4.83  2.89   3.75  1.52  2.08        4     0.0     0.0  ...   
...    ...   ...   ...   ...    ...   ...   ...      ...     ...     ...  ...   
3330     3  3.12  4.09  1.55  10.00  8.01  4.37        1     0.0     0.0  ...   
3331     2  4.20  1.54  2.80   6.95  8.78  2.75        1     0.0     0.0  ...   
3332     3  1.30  3.86  8.07   4.69  6.08  9.86        1     0.0     0.0  ...   
3333     2  2.19  3.76  0.90   4.52  7.26  7.19        1     0.0     0.0  ...   
3334     2  1.83  9.84  2.38   9.57  8.90  5.25        1     0.0     0.0  ...   

      E5kon1  E5kon2  E5kcat  E5koff1  E5koff2  E6kon1  E6kon2  E6kcat  \
0       0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
1       0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
2       0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
3       0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
4       0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
...      ...     ...     ...      ...      ...     ...     ...     ...   
3330    0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
3331    6.98    2.98    4.46     0.90     1.27    0.00    0.00    0.00   
3332    0.00    0.00    0.00     0.00     0.00    0.00    0.00    0.00   
3333    0.00    0.00    0.00     0.00     0.00    7.34    4.02    6.41   
3334    2.53    5.38    7.92     0.38     0.57    0.00    0.00    0.00   

      E6koff1  E6koff2  
0        0.00     0.00  
1        0.00     0.00  
2        0.00     0.00  
3        0.00     0.00  
4        0.00     0.00  
...       ...      ...  
3330     0.00     0.00  
3331     0.00     0.00  
3332     0.00     0.00  
3333     1.02     1.86  
3334     0.00     0.00  

[3335 rows x 38 columns]

In [118]:
predict_ds = KDataset(predict_df)
predict_ds[0]

(array([6.37, 5.09, 3.15, 1.93, 1.32, 0.22, 4.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 3.26, 7.24, 8.31, 0.37, 0.79, 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
        0.  , 0.  , 0.  , 0.  ], dtype=float32),
 tensor([1, 0, 0]))

In [119]:
predictions = np.empty(len(predict_ds))
new_model.eval()

with torch.no_grad():
    for i, input in tqdm(enumerate(data.DataLoader(predict_ds, batch_size=1, shuffle=False)), total=len(predict_ds)):
        raw_predictions = new_model(input[0].to(device))
        predicted_type = torch.argmax(raw_predictions, dim=1) + 1
        predictions[i] = predicted_type

print(predictions)

  0%|          | 0/3335 [00:00<?, ?it/s]

[1. 1. 1. ... 3. 2. 2.]


In [120]:
predict_df.insert(1, "Predicted_Type", [p for p in predictions])
predict_df

Type  Predicted_Type    k1    k2    k3     k4    k5    k6  NumOfEQ  \
0        1             1.0  6.37  5.09  3.15   1.93  1.32  0.22        4   
1        1             1.0  9.56  9.92  8.95   5.84  2.20  4.91        4   
2        1             1.0  2.34  6.50  5.09   0.87  7.58  4.48        4   
3        1             1.0  9.31  3.83  5.20   2.74  6.26  5.36        4   
4        1             1.0  9.32  4.83  2.89   3.75  1.52  2.08        4   
...    ...             ...   ...   ...   ...    ...   ...   ...      ...   
3330     3             2.0  3.12  4.09  1.55  10.00  8.01  4.37        1   
3331     2             2.0  4.20  1.54  2.80   6.95  8.78  2.75        1   
3332     3             3.0  1.30  3.86  8.07   4.69  6.08  9.86        1   
3333     2             2.0  2.19  3.76  0.90   4.52  7.26  7.19        1   
3334     2             2.0  1.83  9.84  2.38   9.57  8.90  5.25        1   

      E1kon1  ...  E5kon1  E5kon2  E5kcat  E5koff1  E5koff2  E6kon1  E6kon2  \
0        0.0  ...    0.00    0.00    0.00     0.00     0.00    0.00    0.00   
1        0.0  ...    0.00    0.00    0.00     0.00     0.00    0.00    0.00   
2        0.0  ...    0.00    0.00    0.00     0.00     0.00    0.00    0.00   
3        0.0  ...    0.00    0.00    0.00     0.00     0.00    0.00    0.00   
4        0.0  ...    0.00    0.00    0.00     0.00     0.00    0.00    0.00   
...      ...  ...     ...     ...     ...      ...      ...     ...     ...   
3330     0.0  ...    0.00    0.00    0.00     0.00     0.00    0.00    0.00   
3331     0.0  ...    6.98    2.98    4.46     0.90     1.27    0.00    0.00   
3332     0.0  ...    0.00    0.00    0.00     0.00     0.00    0.00    0.00   
3333     0.0  ...    0.00    0.00    0.00     0.00     0.00    7.34    4.02   
3334     0.0  ...    2.53    5.38    7.92     0.38     0.57    0.00    0.00   

      E6kcat  E6koff1  E6koff2  
0       0.00     0.00     0.00  
1       0.00     0.00     0.00  
2       0.00     0.00     0.00  
3       0.00     0.00     0.00  
4       0.00     0.00     0.00  
...      ...      ...      ...  
3330    0.00     0.00     0.00  
3331    0.00     0.00     0.00  
3332    0.00     0.00     0.00  
3333    6.41     1.02     1.86  
3334    0.00     0.00     0.00  

[3335 rows x 39 columns]

In [121]:
pred_accuracy = sum(predict_df['Type'] == predict_df['Predicted_Type']) / len(predict_df['Type'])
pred_accuracy

0.886656671664168

In [122]:
predict_df.to_csv('TESZT_AutoCatalysis_parameters_HetCat2_NEW_with_prediction.csv', index=False, sep=';')